# Generated by Django 4.2 on 2023-05-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_book_cover_book_description_book_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
